# this is the library i.e. the called functionality  
name: 'Example2'
description: 'Example2'
inputs:
  input_string:
    description: 'input string'
    required: true
  
runs:
  using: "composite"
  steps:
    - name : Run example in action.yaml
      run: |
        chmod 700 ${{ github.action_path }}/Yo_World.sh
        echo ${{ inputs.input_string }}
        sh  ${{ github.action_path }}/Yo_World.sh "${{ inputs.input_string }}"
      shell: bash
